    -- items
    resource_paydirt            = { name = 'resource_paydirt',            label = 'Paydirt',             weight = 100, type = 'item', image = 'resource_paydirt.png',            unique = false, useable = false, shouldClose = true, description = 'Bucket of dirt and minerals, used by gold rockers.',                          category = 'resource' },    
    tool_goldrocker             = { name = 'tool_goldrocker',             label = 'Gold Rocker',         weight = 100, type = 'item', image = 'tool_goldrocker.png',             unique = false, useable = true, shouldClose = true, description = 'Tool used to separate heavy gold pieces from lighter sand, gravel and dirt.', category = 'tools' },
    tool_rocker_bucket_empty    = { name = 'tool_rocker_bucket_empty',    label = 'Empty Rocker Bucket', weight = 100, type = 'item', image = 'tool_rocker_bucket_empty.png',    unique = false, useable = true, shouldClose = true, description = 'Water bucket used specifically with a gold rocker for panning gold.',         category = 'tools' },
    tool_rocker_bucket_full     = { name = 'tool_rocker_bucket_full',     label = 'Full Rocker Bucket',  weight = 100, type = 'item', image = 'tool_rocker_bucket_full.png',     unique = false, useable = false, shouldClose = true, description = 'Water bucket used specifically with a gold rocker for panning gold.',         category = 'tools' },
    tool_rocker_shovel          = { name = 'tool_rocker_shovel',          label = 'Rocker Shovel',       weight = 100, type = 'item', image = 'tool_rocker_shovel.png',          unique = false, useable = true, shouldClose = true, description = 'Tool panner\'s use for digging and moving loose paydirt soil.',               category = 'tools' },
    resource_gold_claim_license = { name = 'resource_gold_claim_license', label = 'Gold Claim License',  weight = 100, type = 'item', image = 'resource_gold_claim_license.png', unique = false, useable = false, shouldClose = true, description = 'Permit that grants legal right to stake lands for gold.',                     category = 'documents' },
    resource_wood               = { name = 'resource_wood',               label = 'Wood',                weight = 100, type = 'item', image = 'resource_wood.png',               unique = false, useable = true, shouldClose = true, description = 'A hard, fibrous structural tissue found in the stems and roots of trees.',    category = 'lumber' },
    resource_gold_nugget        = { name = 'resource_gold_nugget',        label = 'Gold Nugget',         weight = 100, type = 'item', image = 'resource_gold_nugget.png',        unique = false, useable = true, shouldClose = true, description = 'Nugget found while gold panning.',                                            category = 'resource' },
