    -- rsg-goldclaim items (rocker/claim subsystem)
    ['goldrocker']       = {['name'] = 'goldrocker',       ['label'] = 'Gold Rocker',       ['weight'] = 5000, ['type'] = 'item', ['image'] = 'goldrocker.png',       ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Gold mining equipment'},
    ['goldclaimlicense'] = {['name'] = 'goldclaimlicense', ['label'] = 'Gold Claim License',['weight'] = 100,  ['type'] = 'item', ['image'] = 'goldclaimlicense.png', ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Official gold claim license'},
    ['bucket']           = {['name'] = 'bucket',           ['label'] = 'Bucket',            ['weight'] = 200,  ['type'] = 'item', ['image'] = 'bucket.png',           ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'An empty bucket'},
    ['fullbucket']       = {['name'] = 'fullbucket',       ['label'] = 'Full Bucket',       ['weight'] = 500,  ['type'] = 'item', ['image'] = 'fullbucket.png',       ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'A bucket filled with water'},
    ['shovel']           = {['name'] = 'shovel',           ['label'] = 'Shovel',            ['weight'] = 500,  ['type'] = 'item', ['image'] = 'shovel.png',           ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'A sturdy shovel'},
    ['paydirt']          = {['name'] = 'paydirt',          ['label'] = 'Paydirt',           ['weight'] = 500,  ['type'] = 'item', ['image'] = 'paydirt.png',          ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Dirt that may contain gold'},
    ['wood']             = {['name'] = 'wood',             ['label'] = 'Wood',              ['weight'] = 300,  ['type'] = 'item', ['image'] = 'wood.png',             ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Lumber for repairs'},

    -- rsg-goldclaim items (smelter subsystem)
    ['smelter']          = {['name'] = 'smelter',          ['label'] = 'Smelter',           ['weight'] = 5000, ['type'] = 'item', ['image'] = 'smelter.png',          ['unique'] = false, ['useable'] = true,  ['shouldClose'] = true,  ['combinable'] = nil, ['level'] = 0, ['description'] = 'A portable smelter for refining ores and nuggets'},
    ['silverore']        = {['name'] = 'silverore',        ['label'] = 'Silver Ore',        ['weight'] = 500,  ['type'] = 'item', ['image'] = 'silverore.png',        ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Raw silver ore for smelting'},
    ['silverbar']        = {['name'] = 'silverbar',        ['label'] = 'Silver Bar',        ['weight'] = 2500, ['type'] = 'item', ['image'] = 'silverbar.png',        ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'A bar of refined silver'},

    -- rsg-goldclaim items (shared between rocker + smelter subsystems)
    ['smallnugget']      = {['name'] = 'smallnugget',      ['label'] = 'Small Nugget',      ['weight'] = 100,  ['type'] = 'item', ['image'] = 'smallnugget.png',      ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'A small gold nugget'},
    ['mediumnugget']     = {['name'] = 'mediumnugget',     ['label'] = 'Medium Nugget',     ['weight'] = 200,  ['type'] = 'item', ['image'] = 'mediumnugget.png',     ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'A medium gold nugget'},
    ['largenugget']      = {['name'] = 'largenugget',      ['label'] = 'Large Nugget',      ['weight'] = 300,  ['type'] = 'item', ['image'] = 'largenugget.png',      ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'A large gold nugget'},
    ['goldbar']          = {['name'] = 'goldbar',          ['label'] = 'Gold Bar',          ['weight'] = 3000, ['type'] = 'item', ['image'] = 'goldbar.png',          ['unique'] = false, ['useable'] = false, ['shouldClose'] = false, ['combinable'] = nil, ['level'] = 0, ['description'] = 'A bar of refined gold'},
